### ISSUE TITLE
angular-cli AOT lazy load issue

### ISSUE THREAD

**Issue by achimha** [urish/ngx-moment#114]
The angular ahead of time (AOT) compiler fails when a module does

`import * as moment from 'moment';`

See this ticket: https://github.com/angular/angular-cli/issues/2496 and similar ones. What basically happens is that as soon as there is an import on moment somewhere, generation of bundles for lazily loaded routes fail.

This package is one that breaks AOT lazy loading.

**Comment by rodneyjoyce** [comment]
This issue also breaks the lazy loading chunking - https://github.com/angular/angular-cli/issues/2496

**Comment by achimha** [comment]
Yes, the package is pretty much unusable like this and the bad thing is that this error is very non obvious. Most likely it is caused by webpack.

**Comment by rodneyjoyce** [comment]
Ok, after hours of hacking I have come to the same conclusion:

1) I can get moment and Angular2-moment Pipes working BUT sacrifice lazy-loading and chunking using with AngularCLI the recommend installation method mentioned here. This is not an option for me as I have to use Lazy Loading and chunking.

2) I can get moment (and the Spanish locale) working by itself using the method outlined here https://github.com/angular/angular-cli/issues/2496. HOWEVER, this module (Angular2-Moment will NOT work no matter what I do - it always throws the exception "momentConstructor is not a function"

Therefore I will have to remove Angular2-Moment unfortunately and write my own date formatting pipes until this module is compatible with AngularCLI/Lazy Loading (If I knew how to fix it I would)

**Comment by intellix** [comment]
Workaround for `import * as moment` which uses 50kb is to use a modular library like date-fns instead (28.7kb for me): https://github.com/angular/angular-cli/issues/2496#issuecomment-274272747

**Comment by urish** [comment]
Version 2.0.0 should fix this. Note that the package is now called `ngx-moment` instead of `angular2-moment`. Please open a new issue if this still happens.
