### ISSUE TITLE
Rollup throws 'MomentModule' is not exported

### ISSUE THREAD

**Issue by chicocvenancio** [urish/ngx-moment#115]
**Description of the Issue and Steps to Reproduce:**
Attempt to use angular2-moment with rollup.
It will throw an error. Error: 'MomentModule' is not exported by node_modules\angular2-moment\index.js (imported by app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
Did you search for duplicate issue? [Yes / No]
yes, <s>I am not sure if #114 is related.</s>

*Ensure your issue is isolated to angular2-moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version? 2.2.4
* TypeScript version? 2.0.10
* `moment` version?2.17.1
* Are you using `moment-timezone`? no
* Are you using the angular-cli? 
* Using Rollup/Webpack/System.js/Ionic/similar? 
Rollup, this seems to be fixable <s>with namedExports</s> and be a issue with rollup-plugin-commonjs.

**Comment by urish** [comment]
Hi, any chance you can help by investigating a fix and sending a pull request?

**Comment by chicocvenancio** [comment]
It seems it doesn't need namedExports, but you have to be sure it is in the include section of the plugin.
So my fixed rollup-config.js now reads:
``` javascript
  plugins: [
      nodeResolve({jsnext: true, module: true}),
      commonjs({
        include: 'node_modules/**',
      }),
```
Of course you could just add 
    include: 'node_modules/angular2-moment/**'
but I preferred the more general solution.

As far as a pull request, I figure this is more of a documentation issue. You could add a rolllup comment in the installation section.

**Comment by urish** [comment]
Version 2.0.0 should fix this. Note that the package is now called `ngx-moment` instead of `angular2-moment`. Please open a new issue if this still happens.
