### ISSUE TITLE
(feature) Add `amIsBefore` pipe

### ISSUE THREAD

**Issue by DethAriel** [urish/ngx-moment#118]
The use case I'm envisioning is as follows:

```html
<ul>
  <li *ngFor="let reminder of userReminders" [class.alert]="reminder.dueDate | amIsBefore">
    <my-reminder [reminder]="reminder"></my-reminder>
  </li>
</ul>
```

Basically, I would love the [moment.isBefore()](http://momentjs.com/docs/#/query/is-before/) implemented in this lib as an impure pipe.

**Comment by camillef** [comment]
@urish Is this issue done?

**Comment by urish** [comment]
Yes, closing
