### ISSUE TITLE
(feature): Add locale settings

### ISSUE THREAD

**Issue by Ledzz** [urish/ngx-moment#120]
I would love to change the locale of moment.js. Maybe it can be done with `MomentModule.withConfig({ ... })`? I've managed to set locale by importing native moment module, but this means I need to import one excess module (which is already imported).

**Comment by urish** [comment]
I believe specifying the locale directly on the moment object should do the trick, see #107 for discussion

**Comment by adammartin1981** [comment]
This does work - however if you then change the locale after the pipe has been rendered, it won't update. 

I'm thinking about creating a pull request to implement the non-pure (pure:false) version of the pipes so that they change based on the moment locale changes.

**Comment by FallenRiteMonk** [comment]
If committed a PR which should resolve the problem. #155
