### ISSUE TITLE
How to load locale dynamically

### ISSUE THREAD

**Issue by ramoncarreras** [urish/ngx-moment#126]
I am developing an ionic 2 app. To localize angular2-moment I just included lang module in app.module.ts after including angular2-moment like this and that automatically pulled spanish language:

```
import { MomentModule} from 'angular2-moment';
import 'moment/locale/es';
```

My app use cordova-plugin-globalization to dinamically set app language so, **how can I load the lang locale dynamically**?

Thanks!

**Comment by beaussart** [comment]
Hi, I managed to do so by ` moment. locale ('es'); when a language change is detected, however, I haven't found a way yet to update the currently printed ones.

**Comment by sebrojas14** [comment]
...

**Comment by FallenRiteMonk** [comment]
Anyone found a way to update current printed ones?

**Comment by FallenRiteMonk** [comment]
If committed a PR which should resolve the problem. #155

**Comment by sebrojas14** [comment]
@FallenRiteMonk the pipe soluion requires to set language on each use, and also, the need of inject the current language on every page. Can be set globally?

**Comment by FallenRiteMonk** [comment]
@sebrojas14 it would be possible to change the pipe to use 'moment.locale()' to set the language instead of an input value. In that way one would only have to use the pipe without passing a language to it.

If you want to I could give it a try and create a PR

**Comment by sebrojas14** [comment]
`moment.locale('es')` works for change locale globally but if pipes use `import * as moment from 'moment/min/moment-with-locales';` instead of `import * as moment from 'moment';`. I tried to change tha in this library bu I always get an error (Could not find a declaration file for module 'moment/min/moment-with-locales'. 'c:/Users/Sebastián/Documents/GitHub/angular2-moment/node_modules/moment/min/moment-with-locales.js' implicitly has an 'any' type.   Try `npm install @types/moment/min/moment-with-locales` if it exists or add a new declaration (.d.ts) file containing `declare module 'moment/min/moment-with-locales';`) so I ended up making the pipe in my project (where I can import moment with locales)

**Comment by FallenRiteMonk** [comment]
@sebrojas14 does that also reload already printed/displayed outputs with updated language?

Otherwise try changing the pipes return value from:
```return moment(value).locale(locale);````
to:
```return moment(value).locale(locale? locale : moment.locale());```

That should give one both possibilities, setting it globally and locally, plus it would also keep backward compatibility.

**Comment by D4rkMindz** [comment]
I made a pipe and it worked to actualize the date on a language change:
```javascript
@Pipe({
  name: 'dynamicMoment'
})
export class MomentPipe implements PipeTransform {
  /**
   * MomentPipe constructor
   * @param {TranslateService} translate
   */
  constructor(private translate: TranslateService) {
  }

  /**
   * Make moment dynamic
   * @param {string} value
   * @param {string} format
   * @returns {any}
   */
  transform(value: string, format?: string): any {
    // make the moment format configurable
    format = format ? format : 'MMMM Do YYYY';
    // get the initial value
    const initVal = moment(value).locale(moment.locale()).format(format);
    // insert the value into a new behaviour subject. If the language changes, the behaviour subject will be 
    // updated
    const momentObs = new BehaviorSubject<string>(initVal);
    this.translate.onLangChange.subscribe(() => {
      // format the new date according to the new locale
      const val = moment(value).locale(moment.locale()).format(format);
      momentObs.next(val);
    });
    return momentObs; // needs to be piped into the async pipe
  }

}
```

**Comment by d3v0ps** [comment]
If you're using tools like `ngx-translate` or `@ngneat/transloco` I think the `moment.locale(language)` approach is the cleaner way to follow. I always create a I18nModule in my projects like this one:

```ts

import { ModuleWithProviders, NgModule } from '@angular/core';

import {
  TRANSLOCO_LOADER,
  TRANSLOCO_CONFIG,
  translocoConfig,
  TranslocoModule,
  TranslocoConfig,
  TranslocoService
} from '@ngneat/transloco';

import * as moment from 'moment';
import 'moment/locale/es';

import { I18nHttpLoader } from './loaders/http.loader';

@NgModule({
  exports: [
    TranslocoModule
  ],
})
export class I18nModule {
  static forRoot(config: Partial<TranslocoConfig>): ModuleWithProviders<I18nModule> {
    return {
      ngModule: I18nModule,
      providers: [
        {
          provide: TRANSLOCO_CONFIG,
          useValue: translocoConfig(config)
        },
        { provide: TRANSLOCO_LOADER, useClass: I18nHttpLoader }
      ]
    };
  }

  constructor(private translationService: TranslocoService) {
    this.translationService.langChanges$.subscribe(
      language => moment.locale(language)
    );
  }
}
``
