### ISSUE TITLE
Nativescript Locale

### ISSUE THREAD

**Issue by davorpeic** [urish/ngx-moment#128]
This is not a bug issue, just a way how to use locale in nativescript app in a combo with angular2-moment, tested in iOS, NS 2.5 + Angular

Import module
```
import * as moment from 'moment';
import { MomentModule, DateFormatPipe } from 'angular2-moment';
moment.locale('es');
```

This wasn't working out of the box, so as instructed here https://groups.google.com/forum/#!topic/nativescript/AkUxmZBXZ5M you need to open `node_modules/moment/package.json` and edit this line:
from
```
"main": "./moment.js",
```
to
```
"main": "moment.js",
```

It looks like an NS bug, but not sure if it will be fixed..

**Comment by FahadAlbukhari** [comment]
Good Job.
