### ISSUE TITLE
Angular 4.x support

### ISSUE THREAD

**Issue by mashenoy** [urish/ngx-moment#139]
Does this work with angular 4.x ?

**Comment by urish** [comment]
Yes

**Comment by Walgermo** [comment]
Cant get it to work, says pipe not found. Did as described in the guide .

**Comment by Eraldo** [comment]
I am also having troubles.
I installed the package and added the `MomentModule` in the app imports section.

When using the `amDateFormat` pipe like this `{{date | amDateFormat:'MMM D, Y'}}` I get this error:
```
Error: Uncaught (in promise): Error: Template parse errors:
The pipe 'amDateFormat' could not be found
```

System context:
```
Ionic Framework: ^3.0.1
Ionic App Scripts: 1.3.3
Angular Core: ^4.0.0
Angular Compiler CLI: ^4.0.0
Node: 7.9.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
```

How can I fix this? Any ideas?

**Comment by shavenwalrus** [comment]
Having the same issue.

Works if I import in to the feature module but not if I import in to the app module.

**Comment by mashenoy** [comment]
@shavenwalrus @Eraldo  : I was able to get it to work with Angular 4.x.  

Here is what I had to do
1. Import in the app.module file
2. Add angular2-module  to map & packages in the system.config file.

[Attached by config file below]

**Comment by Eraldo** [comment]
@shavenwalrus Thanks for confirming this issue and hinting to the workaround.
I still want the pipes to be available globally. :)

@mashenoy Ionic (I'm using version 3.x) is using webpack, I don't see any "system.config" file.

**Comment by Ovilia** [comment]
Having the same problem here with Ionic and ng4 here. Waiting...

**Comment by Eraldo** [comment]
Did anyone get this to work?

**Comment by Ovilia** [comment]
@Eraldo It worked for me. It turned out to be that I used the wrong pipe name...

**Comment by Eraldo** [comment]
@Ovilia With a globally imported `MomentModule` and using LazyLoad?

**Comment by Ovilia** [comment]
@Eraldo I think I didn't use LazyLoad...

**Comment by Eraldo** [comment]
I see. I only have the issue when using lazyload.
Thanks for your update. :)

**Comment by Purus** [comment]
I can confirm the same. When using within the individual page's import section, it works fine. But when used in app.module.ts, the pipes are not available with lazy loading.

**Comment by sebrojas14** [comment]
I got this error trying to install 
![image](https://user-images.githubusercontent.com/1771574/27044503-61511e02-4f63-11e7-872e-8763dc0de636.png)

**Comment by Hesesses** [comment]
Did anyone get this working with lazyload?

**Comment by weihsth** [comment]
Normally the module should be added in all modules (app.module and those with lazy loading). Only providers are working app wide if u add it in the app.module. I'll try it the next days on my own...

**Comment by d3viant0ne** [comment]
I'm using this without issue in `4.2.4` implemented in a top level `shared` module which is imported into multiple lazy loaded modules as well as the top level app module.

**Comment by d3viant0ne** [comment]
For those of you having issues, if someone can put up a small, public repro of the issue I'm happy to take a look.

**Comment by Eraldo** [comment]
As a workaround I imported the module into every component where I am using it.

What you are doing @d3viant0ne sounds very smart and 'clean'.
I am wondering: Wouldn't I have to import the shared module in every lazy loaded page/component?
Can you give me a pointer to a tutorial where I can see how to create such shared module?

Thank you for the reply!

**Comment by gerhardcit** [comment]
@Hesesses , yes, you <pagename>.module.ts should also import Angular moment if you are using Lazy loading in Ionic3

```
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { HostsPage } from './hosts';
import { MomentModule } from 'angular2-moment';

@NgModule({
  declarations: [
    HostsPage,
  ],
  imports: [
    IonicPageModule.forChild(HostsPage),
    MomentModule
  ],
})
export class HostsPageModule {}
```

**Comment by alobban** [comment]
I am still having this issue. I have a feature module and it can't find the pipes **amFromUtc** and **amLocal** even with import angular2-moment. 

Am I missing something?

**Comment by alobban** [comment]
Nvm, it seems I had to directly import MomentModule into my Feature Module and using a shared module doesn't work.

**Comment by MT--** [comment]
if you are using a `SharedModule` (which is imported into lazy-loaded feature modules) for common pipes, you will need to include `MomentModule` in your `imports` _and_ `exports`.

**Comment by yurik94** [comment]
@MT-- Imports Array only

**Comment by MT--** [comment]
@yurik94 I would be interested to see a structure where the module does not need to be exported from your Shared module if it is truly a shared module and not another root module that is just globally available. Otherwise, it would seem I need an architecture lesson?

**Comment by urish** [comment]
Should probably be working now with `ngx-moment` 2.0 - please open a new issue if not
