### ISSUE TITLE
add persian language

### ISSUE THREAD

**Issue by hadijahangiri** [urish/ngx-moment#151]
var defaultRelativeTime = {
    future : 'در %s',
    past   : '%s پیش',
    s  : 'چند لحظه پیش',
    ss : '%d ثانیه',
    m  : '1 دقیقه',
    mm : '%d دقیقه',
    h  : '1 ساعت',
    hh : '%d ساعت',
    d  : '1 روز',
    dd : '%d روز',
    M  : '1 ماه',
    MM : '%d ماه',
    y  : '1 سال',
    yy : '%d سال'
};

**Comment by urish** [comment]
Languages are maintained as part of [moment.js](https://github.com/moment/moment). Seems like they already have a [Persian language file](https://github.com/moment/moment/blob/develop/locale/fa.js). If still relevant, please [open an issue there](https://github.com/moment/moment/blob/develop/locale/fa.js)
