### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by FallenRiteMonk** [urish/ngx-moment#156]
Have you ever thougt about renaming the package into something more angular version generel?

Example: ng-moment or ngx-moment

**Comment by urish** [comment]
Ideally, reuse the angular-moment name. But then, we would probably have to rename angular-moment to angularjs-moment or similar. I am not sure this worth all the trouble - but it is open for discussion

**Comment by FallenRiteMonk** [comment]
What about naming it angular-momentjs.

Is angular-moment still under development?

**Comment by GitHubish** [comment]
ngx-moment it's pretty good

**Comment by filipvh** [comment]
I would also prefer a name change, you would need to notify users of the old package
with a deprecation notice on npm-install :)

**Comment by urish** [comment]
ngx-moment it is.

**Comment by urish** [comment]
See #191 for progress
