### ISSUE TITLE
how to used this date format 'MM/DD/YYYY H:MM am/pm' ?

### ISSUE THREAD

**Issue by 02harleen** [urish/ngx-moment#167]
Hi, my custom format is:- MM/DD/YYYY H:MM am/pm 
please tell us how to use this format.

I am using like this:- 
<div>{{ (1503491583 | amFromUnix) | amDateFormat: 'MM/DD/YYYY H:MM am/pm'}}</div>

Output is:- 08/23/2017 18:08 pm3/p3
But my requirement is:- 08/23/2017 18:03 pm

Please tell us how to solve this problem.

**Comment by enesyurtlu** [comment]
For format options read main docs for MomentJS - https://momentjs.com/docs/#/displaying/

**Comment by Delagen** [comment]
RTFM. Wrong format string used
