### ISSUE TITLE
Only include the required locales

### ISSUE THREAD

**Issue by jawadst** [urish/ngx-moment#168]
It looks like all the locales are included by default (even in a prod build) and they are pretty heavy.
Would it be possible to not include any locale by default and then let us decide which ones to add to our projects? Potentially, putting moment as a peer dependency would be good enough.

**Comment by vecernik** [comment]
+1 please

**Comment by satsangswami** [comment]
A small hack can be.
1. rename `/node_modules/moment/locale` to `/node_modules/moment/locale_`
2. add new folder `/node_modules/moment/locale`
3. copy the `<desired_locale>.js` in the newly created folder.

This is **NOT** an ethical approach, but however will be useful for time-being until next update to the master.

**Comment by deeg** [comment]
If using webpack you can do: `new IgnorePlugin(/\.\/locale$/, /node_modules.+(moment)/),`
