### ISSUE TITLE
Angular AOT support

### ISSUE THREAD

**Issue by sergey-morenets** [urish/ngx-moment#170]
Hi

I am using the latest version of angular2-moment and unable to build project using AOT compilation. When I do rollup stage I get error message:

'MomentModule' is not exported by 'node_modules\angular2-moment\moment.module.js'
[!] Error: 'MomentModule' is not exported by node_modules\angular2-moment\index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src\app\shop\shop.module.js (17:9)
17: import { MomentModule } from "angular2-moment";

* Angular version? 
4.3.6

* TypeScript version?
1.4.2

* `moment` version?
2.18.1

* Are you using the angular-cli? 
1.4.1

* Using Rollup/Webpack/System.js/Ionic/similar? 
Angular CLI + Rollup

Thanks.

**Comment by urish** [comment]
Version 2.0.0 should fix this. Note that the package is now called `ngx-moment` instead of `angular2-moment`. Please open a new issue if this still happens.
