### ISSUE TITLE
The pipe "amFromUtc" could not be found, with Node 8.5.0

### ISSUE THREAD

**Issue by carol-braileanu** [urish/ngx-moment#171]
**Description of the Issue and Steps to Reproduce:**
I have a project that is building fine with Node 7.9.0. I have `MomentModule` imported and exported in a `SharedModule`, which is imported in my AppModule.

```
const MODULES_IMPORT = [
    .........
    MomentModule,
    ....
 ];
const MODULES_EXPORT = [
    ....
    MomentModule,
    ...
 ];

const COMPONENTS = [
    ...
    ];

const SERVICES = [
    ...

];

const PIPES = [ ... ];
const DIRECTIVES = [ ... ];

@NgModule({
  declarations: [
      ...COMPONENTS,
      ...PIPES,
      ...DIRECTIVES,
  ],
  imports: [
      ...MODULES_IMPORT
  ],
  providers: [
      ...SERVICES
  ],
  exports: [
      ...MODULES_EXPORT,
      ...COMPONENTS,
      ...PIPES,
      ...DIRECTIVES,
  ]
})
export class SharedModule { 
static forRoot(config: ApplicationConfig): ModuleWithProviders {
        return {
		ngModule: SharedModule,
		providers: [
		  { provide: ApplicationConfig, useValue: config }
		]
	  };
	}
}

```
I import this in my main module using `SharedModule.forRoot(settings)`.

I am using the Moment pipes in a component inside the `SharedModule`:
`<small class="text-muted"><i class="fa subicon fa-clock-o"></i> {{m.timestamp | amFromUtc | amTimeAgo}}</small>`

As I mentioned, it works fine with Node 7.9.0, but with 8.5.0 I get the following error:

```
[11:49:21]	[Step 6/8] ERROR in Template parse errors:
[11:49:21]	[Step 6/8] The pipe 'amFromUtc' could not be found (")">
[11:49:21]	[Step 6/8] </span><br />
[11:49:21]	[Step 6/8] <small class="text-muted"><i class="fa subicon fa-clock-o"></i> {{[ERROR ->]m.timestamp | amFromUtc | amTimeAgo}}</small>
[11:49:21]	[Step 6/8] </div>
[11:49:21]	[Step 6/8] </div>
```

Did you search for duplicate issue? [Yes]

**Environment:**

* Angular version?  4.4.1
* TypeScript version? 2.5.2
* `moment` version? 2.18.1
* Are you using `moment-timezone`? No
* Are you using the angular-cli? Yes
* Using Rollup/Webpack/System.js/Ionic/similar?

**Comment by kevado** [comment]
The `amFromUtc` pipe was added to angular2-moment@1.7.0 -- you are probably using 1.6.0.
