### ISSUE TITLE
Is there any support of angular-cli for this package ?

### ISSUE THREAD

**Issue by amaneer94** [urish/ngx-moment#173]
**Description of the Issue and Steps to Reproduce:**

> I am facing installation issue. Also tried typings but still disappointed.

Did you search for duplicate issue? [Yes / No]

> YES. but could not find any post issue for angular-cli

![issue npm angular2-moment installation](https://user-images.githubusercontent.com/16270049/30863255-053daa2e-a2ea-11e7-9b4c-4db11f2a5a0f.PNG)

*Ensure your issue is isolated to angular2-moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version? 
* TypeScript version?
* `moment` version?
* Are you using `moment-timezone`? 
* Are you using the angular-cli? 
* Using Rollup/Webpack/System.js/Ionic/similar? 

> Please check attached file.

**Comment by amaneer94** [comment]
Package seems to be installed. But when i try to import the `MomentModule` module. It shows lint/build error when imported. 
![issue npm angular2-moment installation 22](https://user-images.githubusercontent.com/16270049/30863792-5c39820c-a2eb-11e7-8282-7bb06e607524.PNG)

**Comment by urish** [comment]
Version 2.0.0 should fix this. Note that the package is now called `ngx-moment` instead of `angular2-moment`. Please open a new issue if this still happens.
