### ISSUE TITLE
UNMET PEER Dependency when installing

### ISSUE THREAD

**Issue by fredlemieux** [urish/ngx-moment#189]
Hi there,

This might be an issue related to Angular rather than angular2-moment.  However, I'm stuck so hopefully someone can point me in the right direction.  I've been working on a project using [ngx-admin demo](https://github.com/akveo/ngx-admin), I could really use the angular2-moment pipes.  However, when I using npm install angular2-moment --save it give me the following UNMET PEER DEPENDENCIES:

+-- UNMET PEER DEPENDENCY @angular/common@5.2.9
+-- UNMET PEER DEPENDENCY @angular/compiler@5.2.9
+-- UNMET PEER DEPENDENCY @angular/core@5.2.9
+-- UNMET PEER DEPENDENCY @angular/forms@5.2.9
+-- angular2-moment@1.8.0
+-- UNMET PEER DEPENDENCY jquery@1.9.1 - 3
`-- UNMET PEER DEPENDENCY popper.js@^1.12.9

My dependencies for my project are as follows:
"dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "~5.2.6",
    "@angular/common": "~5.2.6",
    "@angular/compiler": "~5.2.6",
    "@angular/core": "~5.2.6",
    "@angular/forms": "~5.2.6",
    "@angular/http": "~5.2.6",
    "@angular/platform-browser": "~5.2.6",
    "@angular/platform-browser-dynamic": "~5.2.6",
    "@angular/router": "~5.2.6",
    "@asymmetrik/ngx-leaflet": "3.0.1",
    "@nebular/auth": "2.0.0-rc.6",
    "@nebular/security": "2.0.0-rc.6",
    "@nebular/theme": "2.0.0-rc.6",
    "@ng-bootstrap/ng-bootstrap": "1.0.0",
    "@swimlane/ngx-charts": "7.0.1",
    "angular2-chartjs": "0.4.1",
    "angular2-toaster": "4.0.1",
    "bootstrap": "4.0.0",
    "chart.js": "2.7.1",
    "ckeditor": "4.7.3",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.1",
    "echarts": "^4.0.2",
    "font-awesome": "4.7.0",
    "intl": "1.2.5",
    "ionicons": "2.0.1",
    "leaflet": "1.2.0",
    "nebular-icons": "1.0.6",
    "ng2-ckeditor": "1.1.13",
    "ng2-smart-table": "1.2.2",
    "ng2-tree": "2.0.0-rc.4",
    "ngx-echarts": "2.0.1",
    "normalize.css": "6.0.0",
    "pace-js": "1.0.2",
    "roboto-fontface": "0.8.0",
    "rxjs": "5.5.5",
    "socicon": "3.0.5",
    "tinymce": "4.5.7",
    "typeface-exo": "0.0.22",
    "web-animations-js": "2.2.5",
    "zone.js": "0.8.18"
  },

I've tried deleting all node_modules folder, and changing the dependencies in the package.json file so that it includes the popper.js and jquery packages, also updating the versions of the angular packages to match the UNMET PEER DEPENDENCY error message i.e.:
 "@angular/common": "5.2.9", and so on

I've also tried using the caret:  "@angular/common": "^5.2.6",

It doesn't make a difference, I still get the error.  Can anyone explain how to resolve this issue?

**Comment by urish** [comment]
Seems like it could be related to some other third-party library you are using - neithe popper.js nor jquery are needed by ngx-moment or angular
