### ISSUE TITLE
Incomplete install instructions

### ISSUE THREAD

**Issue by BrummbQ** [urish/ngx-moment#194]
Hello!

Since you added moment as a peer dependency, a user must install moment.js first before using this package, else the build just fails with `Cannot find module 'moment'.`

I think you should the users about this, maybe even list moment in the npm install command

**Comment by urish** [comment]
Thanks! released as 3.0.1

**Comment by nohanna** [comment]
Hey,

I don't know if I am the only one in this case but I've still this error with the 3.0.1 version and have to install moment.js.

Any suggestions?

**Comment by BrummbQ** [comment]
yeah, I mean thats the point? You need to install both packages as instructed

**Comment by nohanna** [comment]
Oh ok, thought it was just for system.js users.

Thanks
