### ISSUE TITLE
remove locale from moment in angular2/4

### ISSUE THREAD

**Issue by jainAdijain** [urish/ngx-moment#197]
I am using angular2-moment in ionic-angular application

In a certain component's module I am using 

**package.json**

 `"angular2-moment": "^1.7.0",`

```
import {MomentModule} from 'angular2-moment';

@ngModule({
imports: [ MomentModule ] 
})
```

**.html**

<div>using `amTimeAgo` pipe</div>

The source maps generated for this module shows locale which increases the size of the overall vendor.

![image](https://user-images.githubusercontent.com/27722458/42019072-b8ac36a6-7ad1-11e8-9c0a-a788e42712e0.png)

How to remove this locale?

**Comment by urish** [comment]
#127 and #168 has some workarounds. Here is what I do in my projects (using the Angular CLI):

1. Install moment version 2.22.0 (newer versions will work with slight adaptations):
```shell
    npm i --save moment@2.22.0
```

2. Install [patch-package](https://www.npmjs.com/package/patch-package) and add it to your package.json inside the scripts section:
```json
{
  "scripts": {
    "prepare": "patch-package"
  }
}
```

3. Create a file under `patches/moment+2.22.0.patch` with the following content:
```patch
patch-package
--- a/node_modules/moment/moment.js
+++ b/node_modules/moment/moment.js
@@ -1832,7 +1832,7 @@
                 module && module.exports) {
             try {
                 oldLocale = globalLocale._abbr;
-                var aliasedRequire = require;
+                var aliasedRequire = eval('require');
                 aliasedRequire('./locale/' + name);
                 getSetGlobalLocale(oldLocale);
             } catch (e) {}
--- a/node_modules/moment/src/lib/locale/locales.js
+++ b/node_modules/moment/src/lib/locale/locales.js
@@ -52,7 +52,7 @@ function loadLocale(name) {
             module && module.exports) {
         try {
             oldLocale = globalLocale._abbr;
-            var aliasedRequire = require;
+            var aliasedRequire = eval('require');
             aliasedRequire('./locale/' + name);
             getSetGlobalLocale(oldLocale);
         } catch (e) {}
```

4. Run `npm run prepare` to apply to patch. It will also be applied automatically by patch-package whenever you `npm install`.

This workaround makes sure moment does not implicitly bundle any locales - unless you import specific locales that you are interested in.

**Comment by alexcoroza** [comment]
Then where should I create the "patches" folder?
