### ISSUE TITLE
Is there an way to use amTimeAgo in the component class not in the template html.

### ISSUE THREAD

**Issue by avinashrg94** [urish/ngx-moment#199]
Custom pipe we can use it in the component with pipeName.transform(value). In the same way is it possible to use moment pipes like amTimeAgo, amCalendar,etc.. in the component class ?

**Comment by clarencecastillo** [comment]
Yes you can. To use the `amTimeAgo` pipe in the component class, add `MomentModule` to your module imports and add `TimeAgoPipe` into your module providers.

```ts
import { MomentModule, TimeAgoPipe } from 'ngx-moment';

@NgModule({
  imports: [
    ...,
    MomentModule
  ],
  providers: [
    TimeAgoPipe
  ]
})
export class MyPageModule {}
```

In your component's class, inject it as you would with your services and then you can call `transform(value, ...args)` wherever you need it.

```ts
import { TimeAgoPipe } from 'ngx-moment';

@Component({
  ...
})
export class MyPageComponent {
  constructor(
    private timeAgoPipe: TimeAgoPipe
  ) { }
  
  someFunction() {
    this.timeAgoPipe.transform(...);
  }
}
```
