### ISSUE TITLE
Does this work with Angular 6.0?

### ISSUE THREAD

**Issue by jungalwala** [urish/ngx-moment#200]
When installing with an Angular 6.0 project, I get the following error:

npm WARN angular2-moment@1.9.0 requires a peer of @angular/core@>=2.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself.

I am running

    "@angular/core": "^6.0.0",

**Comment by urish** [comment]
For angular 6, please install `ngx-moment` instead of `angular2-moment`
