### ISSUE TITLE
Angular 7

### ISSUE THREAD

**Issue by IlCallo** [urish/ngx-moment#203]
**I'm submitting a ...**
feature request

**What is the motivation / use case for changing the behavior?**
Angular 7 is out, library should be checked for compatibility and peerDependencies should be updated

**Comment by samfrach** [comment]
please upgrade :)

**Comment by jaysaikia** [comment]
+1

**Comment by salcio** [comment]
+1

**Comment by urish** [comment]
Just released as 3.2.0
