### ISSUE TITLE
ngx-moment.umd.js vs index.js

### ISSUE THREAD

**Issue by nickhod** [urish/ngx-moment#211]
I recently upgraded from angular2-moment to ngx-moment 3.3.0.

I couldn't get ngx-moment to work following the documentation
```
'ngx-moment': {
                main: './index.js',
                defaultExtension: 'js'
 }
```
index.js doesn't exist in the package so I got 404s.

Changing it to 

```
 'ngx-moment': {
                main: './bundles/ngx-moment.umd.js',
                defaultExtension: 'js'
}
```

did work. Does your documentation need updating or am I doing something wrong?

**Comment by Delagen** [comment]
Published 6.0.2 version with partial ivy compilation, so I think this issue is outdated
