### ISSUE TITLE
Tslib missing from package.json file

### ISSUE THREAD

**Issue by AMBudnik** [urish/ngx-moment#216]
**Description of the Issue and Steps to Reproduce:**

Hey,

I was checking this repository and spotted that on NPM you're having the `tslib` as a dependency but it's missing in the `package.json` file. Versions are the same for both sources - `3.4.0`

**Comment by urish** [comment]
Yes, it's added automatically by the Angular CLI whenever you run `ng build`. 

As far as I can tell, this is the intended behavior. Check out angular/angular-cli#13886 and ng-packagr/ng-packagr#1159 for more information.

**Comment by AMBudnik** [comment]
Oh, that's interesting. Thanks @urish

**Comment by urish** [comment]
You are welcome :-)
