### ISSUE TITLE
[docs] improve docs, how to import to core module

### ISSUE THREAD

**Issue by borriej** [urish/ngx-moment#229]
hi,

I tried adding MomentModule to my Core Module:

```
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    NgProgressModule.withConfig(Globals.loadingBar),
    NgProgressHttpModule,
    ToastrModule.forRoot(Globals.toast),
    CookieModule.forRoot(),
    ToastContainerModule,
    MomentModule,
    SharedModule
  ],
```

then using the AmTimeAgo pipe in a Lazy Loaded sub module (which does not include CoreModule offcourse):
```
{{ object.date | amTimeAgo }}
```

but getting the error:
```
The pipe 'amTimeAgo' could not be found 
```

How do you import the MomentModule inside a CoreModule?

**Comment by urish** [comment]
I believe the lazy module has to import `MomentModule` as well in order to use the pipes defined there (pipes are not global, they are only available for modules that imported them)
