### ISSUE TITLE
can't use amLocale with amLocal

### ISSUE THREAD

**Issue by ahmedkhairydev** [urish/ngx-moment#238]
**Description of the Issue and Steps to Reproduce:**

Did you search for duplicate issue? [Yes / No]
Yes.

I can't use amLocale with amLocal. amLocal doesn't work correctly.
amLocal  working correctly when using it without amLocale.
when using amLocal the time becomes to be in Arabic character

```
<span class="time">{{ row.dateModified | amLocale: 'en' | amFromUtc | amLocal | amDateFormat: 'hh:mm a' }}</span>
```

**Preview**
![image](https://user-images.githubusercontent.com/15922118/84249239-cc125e80-ab0a-11ea-87d2-1b2f176406da.png)

**Version** 
```
"moment": "^2.24.0",
"ngx-moment": "^3.5.0",
"moment-hijri": "^2.1.2"
```

**Environment:**
* Angular version

**Comment by sergey-morenets** [comment]
Hi @ahmedkhairydev 

Just tested with ngx-moment 5.0. Locale was chosen correctly.

**Comment by ahmedkhairydev** [comment]
@sergey-morenets I texted it but still not working correctly.

``{{ row.dateCreated | amLocal | amDateFormat: 'DD/MM/YYYY hh:mm a' }}``

the date appears as an Arabic character also.
![image](https://user-images.githubusercontent.com/15922118/92375101-edcab400-f100-11ea-838f-fd22ab161562.png)

it should be
![image](https://user-images.githubusercontent.com/15922118/92375204-1652ae00-f101-11ea-8ae9-0381b76ddf49.png)

**Comment by ahmedkhairydev** [comment]
Hi @sergey-morenets 

Thanks for your support
The issue is resolved but the sequence of the pipes should be correct! 😂

**Right Way**
```
<span class="time"> {{ row.dateModified | amFromUtc | amLocal | amLocale: 'en' | amDateFormat: 'hh:mm a'  }} </span>
```
**Wrong Way**
```
<span class="time"> {{ row.dateModified  | amLocale: 'en' | amFromUtc | amLocal | amDateFormat: 'hh:mm a'  }} </span>
```
