### ISSUE TITLE
ModuleWithProviders usage without type parameter no longer supported in angular 10.

### ISSUE THREAD

**Issue by FrancisS** [urish/ngx-moment#240]
https://github.com/urish/ngx-moment/blob/ba26f85b6eebc75b65ba85739ba3e74ea5dee648/src/moment.module.ts#L45

Support for using the ModuleWithProviders without a generic parameter has been removed as of angular 10. ngx-moment no longer compiles with angular 10.

node_modules/ngx-moment/moment.module.d.ts:4:49 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

4     static forRoot(options?: NgxMomentOptions): ModuleWithProviders;

**Comment by urish** [comment]
Thank you!

**Comment by urish** [comment]
Released as 5.0.0
