### ISSUE TITLE
momentConstructor$a is not a function

### ISSUE THREAD

**Issue by weini01** [urish/ngx-moment#245]
Hi, I am getting the following error if I use an ngx-moment pipe. Does anybody know how to fix this, I am searching for days. 

```
ERROR TypeError: momentConstructor$a is not a function
at TimeAgoPipe.createTimer (modules.js?hash=c8c18acd318de84d628fd2f193bd914f3054af15:140401)
at TimeAgoPipe.transform (modules.js?hash=c8c18acd318de84d628fd2f193bd914f3054af15:140390)
```

**Environment:**

Please answer the following questions:

* Angular version: 9.1.12
* TypeScript version: 3.7.5
* `moment` version: ^2.24.0
* Are you using `moment-timezone`: no
* Are you using the angular-cli: no
* Using Rollup/Webpack/System.js/Ionic/similar: angular-meteor

**Comment by dima-gusyatiner** [comment]
I also get this error.
````
momentConstructor$1 is not a function
````
