### ISSUE TITLE
i get warnings about pipes not being found despite importing everything

### ISSUE THREAD

**Issue by beppe9000** [urish/ngx-moment#246]
it is a problem similar to #207 which may have been closed without a proper solution. the key difference for me is that it is compiled successfully and works in browser, but visual studio code complains. is there a way to suppress the warning or solve it ?
![image](https://user-images.githubusercontent.com/6625123/99816956-960ee700-2b4c-11eb-878a-ded7fc122914.png)

**Comment by vadimwe** [comment]
Did you import MomentModule in your component module?

**Comment by beppe9000** [comment]
in the end i fixed this by refreshing node_modules folder but i don't think it was the only factor
